spring:
  application:
    name: Blab
  datasource:
    username: ${DB_USERNAME}
    password: ""
    url: jdbc:h2:mem:blabdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info